NumPy adalah <i>library</i>/modul dalam bahasa pemrograman python yang digunakan untuk komputasi saintifik. Untuk menggunakan <i>framework</i> ini kalian harus sudah memasang pip terlebih dahulu, kemudian pada terminal/cmd ketik perintah berikut :
<br><br><b>pip install numpy</b> atau <b>pip3 install numpy</b>
<br><br>Setelah proses pemasangan selesai NumPy siap digunakan!

In [1]:
import numpy as np

In [2]:
a  = np.array([1,2,3,4,5])
aa = np.array([7,2.3,4,5,6])
b  = [1,2,3,4,5]

Variabel a berisi array NumPy yang seluruh datanya bertipe <i>integer</i>
<br>Variabel aa berisi array NumPy yang data-datanya ada yang bertipe <i>float</i> ataupun <i>integer</i>
<br>Variabel b berisi list Python yang seluruh datanya bertipe <i>integer</i>

In [3]:
print("Array NumPy  : ", a)
print("Array NumPy  : ", aa)
print("List Python  : ", b)

Array NumPy  :  [1 2 3 4 5]
Array NumPy  :  [7.  2.3 4.  5.  6. ]
List Python  :  [1, 2, 3, 4, 5]


List dapat menampung data dengan berbagai macam tipe data namun array pada NumPy layaknya array pada bahasa pemrograman lain yang hanya dapat menyimpan himpunan data dengan satu macam tipe data saja. Oleh karena itu pada variabel aa seluruh himpunan data otomatis berubah ke <i>float</i> meskipun ada data yang awalnya bertipe <i>integer</i>. Terdapat perbedaan yang lain, yakni pada saat mencetak array NumPy tidak ada tanda koma seperti list pada Python

Kita coba menjumlahkan array dengan bilangan skalar

In [4]:
a = a + 1
b = b + [1]

In [5]:
print("Array NumPy  : ", a)
print("List Python : ", b)

Array NumPy  :  [2 3 4 5 6]
List Python :  [1, 2, 3, 4, 5, 1]


Pada variabel a yang menggunakan array NumPy seluruh nilai data akan ditambah dengan 1 yang pada awalnya [1 2 3 4 5] menjadi [2 3 4 5 6]. Beda dengan variabel b, variabel b bertipe data list, kita tidak dapat menambahkan tipe data list dengan suatu nilai yang bukan bertipe data list oleh karena itu nilai 1 harus kita ubah menjadi tipe data list([1]) terlebih dahulu. Hasilnya, nilai satu akan menjadi anggota list pada variabel b yang terletak di akhir indeks.

## Fungsi-fungsi Dasar

<b>arange()

In [6]:
c = np.arange(1,10,2)

print(c)

[1 3 5 7 9]


Terdapat 3 argumen pada fungsi arange() di atas. Maksudnya adalah :
<br><b>1</b> adalah awal dari himpunan data pada variabel c
<br><b>10</b> adalah batas akhir/akhir dari himpunan data pada variabel c. Setiap nilai dari batas akhir akan dikurangi 1(sama seperti ketika mengakses indeks pada list Python) jadi apabila kita masukkan 10 maka yang menjadi batas akhirnya adalah 9(10-1)
<br><b>2</b> adalah jarak tiap data

In [7]:
c[1]   # Mengakses indeks ke 1

3

<b>linspace()

In [8]:
d = np.linspace(1,10,4)

print(d)

[ 1.  4.  7. 10.]


Menampilkan 4 angka di dalam range 1-10 dengan jarak yang sama
<br>Data yang keluar bertipe <i>float</i> karena terdapat operasi pembagian di dalamnya sehingga tidak menutup kemungkinan outputnya bukan <i>integer</i>

<b>zeros()

In [9]:
e = np.zeros((5,5))

print(e)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Membuat dan menampilkan matriks berukuran 5x5 yang seluruh nilainya 0<br>
Tipe data <i>default</i>nya adalah <i>float</i>

<b>ones()

In [10]:
f = np.ones((5,5))

print(f)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Membuat dan menampilkan matriks berukuran 5x5 yang seluruh nilainya 1<br>
Tipe data <i>default</i>nya adalah <i>float</i>

<b>identity()</b> dan <b>eye()

In [11]:
f1 = np.identity(5)
f2 = np.eye(5)

In [12]:
print(f1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
print(f2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Untuk membuat matriks identitas berukuran 5x5
<br>Tipe data <i>default</i>nya adalah <i>float</i>
<br>Dinamakan eye karena menyesuaikan penyebutan I(<i>identity</i>) dalam bahasa inggris
<br>fungsi identity() hanya menampilkan matriks identitas saja sedangkan fungsi eye() lebih kompleks sedikit
<br>Baca lebih lanjut sendiri https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html

<b>Matriks

In [14]:
e = np.array([(1,2,3),(4,5,6)])   # Format penulisan untuk membuat matriks dengan array NumPy

print(e)

[[1 2 3]
 [4 5 6]]


## Operasi Aritmatika

Buat array NumPy yang baru

In [15]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]

anp = np.array([1,2,3,4,5])
bnp = np.array([6,7,8,9,10])

<b>1. Penjumlahan (+)

In [16]:
print("Penjumlahan list Python : ",a+b)
print("Penjumlahan array NumPy : ",anp+bnp)

Penjumlahan list Python :  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Penjumlahan array NumPy :  [ 7  9 11 13 15]


<b>2. Pengurangan (-)

In [17]:
print("Pengurangan array NumPy : ",anp-bnp)

Pengurangan array NumPy :  [-5 -5 -5 -5 -5]


Tidak bisa melakukan operasi pengurangan pada sesama list Python
<br>contohnya :

In [18]:
print("Pengurangan array NumPy : ",a-b)

TypeError: unsupported operand type(s) for -: 'list' and 'list'

<b>3. Perkalian (*)

In [19]:
print("Perkalian array NumPy : ",anp*bnp)

Perkalian array NumPy :  [ 6 14 24 36 50]


Tidak bisa melakukan operasi perkalian pada sesama list Python
<br>contohnya :

In [20]:
print("Perkalian array NumPy : ",a*b)

TypeError: can't multiply sequence by non-int of type 'list'

<b>4. Pembagian (/)

In [21]:
print("Pembagian array NumPy : ",anp/bnp)

Pembagian array NumPy :  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


Tidak bisa melakukan operasi pembagian pada sesama list Python
<br>contohnya :

In [22]:
print("Pembagian array NumPy : ",a/b)

TypeError: unsupported operand type(s) for /: 'list' and 'list'

<b>5. Matriks

In [23]:
c = np.array([(1,2,3),(4,5,6)])
d = np.array([(7,8,9),(10,11,12)])

print(c+d)   # Hasil penjumlahan
print(c*d)   # Hasil perkalian
print(c-d)   # Hasil pengurangan
print(c/d)   # Hasil pembagian

[[ 8 10 12]
 [14 16 18]]
[[ 7 16 27]
 [40 55 72]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Perkalian matriks biasa tidak sama dengan perkalian matriks numpy karena operasi aritmatika pada numpy menggunakan <i>element wise operation</i> sehingga tiap-tiap nilai akan dioperasikan satu persatu sesuai dengan urutan indeksnya sehingga tidak(otomatis) menyesuaikan dengan kaidah perkalian matriks pada umumnya

<center><b>Sekian semoga bermanfaat (: