Sebelum membaca lebih lanjut, wajib bagi kalian untuk mengetahui konsep dan penerapan <a href="https://github.com/mrizkir/learndatascience/blob/master/2_dasar_pemrograman_python/3_struktur_data_list_tuple_set.ipynb"><i>list</i></a> pada Python karena materi tentang pengindeksan, pengirisan, dan iterasi pada NumPy itu sangat berhubungan dengan operasi-operasi yang ada pada <i>list</i>.

In [1]:
import numpy as np

### Buat array

In [2]:
BilPang2 = np.arange(10)**2
print(BilPang2)

[ 0  1  4  9 16 25 36 49 64 81]


<i>Array</i> yang barusan kita buat di atas itu isinya sepuluh bilangan pangkat dua pertama.<br>
Ingat <i>array</i> pada Python dimulai dari 0, tidak seperti Matlab dan R yang dimulai dari 1 :V

### Buat matriks

In [3]:
def f(x,y):
    return 10*x+y

# Matriks dengan 5 baris dan 4 kolom di mana semua datanya bertipe int
Matriks = np.fromfunction(f,(5,4),dtype=int)
print(Matriks)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


<i>Kok bisa gitu? '-'</i><br>
Gini-gini, jadi kan ada fungsi f yang punya argumen/parameter x dan y tuh<br>
terus isinya berupa nilai kembalian dari 10 * x + y kan?<br>
Coba perhatikan satu persatu kolom pada matriks di atas, nilai x dan y itu sama-sama dimulai dari 0 oleh karena itu pada kolom pertama(paling kiri) itu isinya dari perhitungan ini :<br>
0 <= asalnya dari : 10 * 0 + 0<br>
10 <= asalnya dari : 10 * 1 + 0<br>
20 <= asalnya dari : 10 * 2 + 0<br>
30 <= asalnya dari : 10 * 3 + 0<br>
40 <= asalnya dari : 10 * 4 + 0<br>

Paham kan? <i>Kudu paham dong '-'</i><br>
Begitu juga dengan kolom kedua :<br>
1 <= asalnya dari : 10 * 0 + 1<br>
11 <= asalnya dari : 10 * 1 + 1<br>
21 <= asalnya dari : 10 * 2 + 1<br>
31 <= asalnya dari : 10 * 3 + 1<br>
41 <= asalnya dari : 10 * 4 + 1<br>Begitupun seterusnya...

O iya fungsi <b>fromfunction()</b> itu gunanya buat bikin <i>array</i>/matriks yang nilainya berdasarkan nilai kembalian dari sebuah fungsi.<br>
Argumen/parameter <b>fromfunction</b> itu ada 3, yaitu fungsi, betuk(dimensi) <i>array</i>/matriks, sama tipe data.

## Pengindeksan

#### 1. <i>Array</i>

In [4]:
print(BilPang2)

[ 0  1  4  9 16 25 36 49 64 81]


Untuk mengambil nilai pada NumPy itu caranya sama ya kayak ambil nilai (pengindeksan) pada <i>list</i>'nya Python.<br>

In [5]:
print("Nilai dari indeks kedelapan :",BilPang2[8])
print("Nilai dari indeks terakhir :",BilPang2[-1])

Nilai dari indeks kedelapan : 64
Nilai dari indeks terakhir : 81


Gunakan kata kunci <b>shape</b> untuk mengetahui bentuk/dimensi dari suatu <i>array</i>/matriks yang telah kalian buat.

In [6]:
print(BilPang2.shape)

(10,)


Jika nilai yang ditampilkan sama dengan jumlah elemen dari <i>array</i> maka array tersebut adalah <i>array</i> satu dimensi.

#### 2. Matriks

In [7]:
print(Matriks)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [8]:
print(Matriks.shape)

(5, 4)


Ukuran matriksnya sama'kan? 5x4<br>
5 baris 4 kolom. Ehehe

Kalo mau ambil nilai/elemen dari sebuah matriks itu formatnya :<br>

<b>nama_array[indeks baris, indeks_kolom]<b>

In [9]:
print(Matriks[2,3])

23


itu artinya ambil nilai Matriks dari baris ke 2 (dari 0, selalu ingat bahwa indeks selalu dimulai dari 0) dan kolom ke 3.<br>Jadi hasilnya 23 deh...

## Pengirisan

#### 1. <i>Array</i>

In [10]:
print(BilPang2)

[ 0  1  4  9 16 25 36 49 64 81]


Mengambil nilai dari indeks ke 2 sampai 4(5-1)

In [11]:
print(BilPang2[2:5])

[ 4  9 16]


Ndak perlu saya jelaskan lagi ya kenapa outputnya 4 9 16<br>
Silahkan baca kalimat di atas tulisan <b>import numpy as np</b> kalo belum paham ehehe

In [12]:
BilPang2[2:10:2] = 4
print(BilPang2)

[ 0  1  4  9  4 25  4 49  4 81]


Itu maksudnya mulai dari indeks ke 2 sampai indeks ke 9(10-1) ubah nilai <i>array</i> yang memiliki urutan ke 2 dan kelipatannya menjadi 4.

In [13]:
type("40")

str

In [14]:
BilPang2[2:10:2] = "40"   # bertipe string
print(BilPang2)

[ 0  1 40  9 40 25 40 49 40 81]


Ternyata si numpy <i>array</i> ini mau nerima nilai bertipe <i>string</i> nih.<br>
Asalkan isi dari string tersebut adalah angka lo ya.<br>

In [15]:
BilPang2[2:10:2] = "Genap"   # bertipe string
BilPang2

ValueError: invalid literal for int() with base 10: 'Genap'

Kalo mau merubah urutan nilainya berdasarkan indeks

In [16]:
BilPang2[ : :-1]

array([81, 40, 49, 40, 25, 40,  9, 40,  1,  0])

#### 2. Matriks

In [17]:
print(Matriks)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


Ambil baris kedua

In [18]:
b = Matriks[1]
print(b)

[10 11 12 13]


Ambil kolom kedua

In [19]:
print(Matriks[0:5,1])

[ 1 11 21 31 41]


Keluaran baris kode di atas sama dengan baris kode yang di bawah :

In [20]:
print(Matriks[ : ,1])

[ 1 11 21 31 41]


Silahkan pahami sendiri :V<br>
Gampang kok :)

Ambil baris kedua dan ketiga

In [21]:
print(Matriks[1:3, : ])

[[10 11 12 13]
 [20 21 22 23]]


Pengirisan di <i>list</i> sama aja sih sama pengirisan di NumPy <i>array</i>.<br>
Soalnya matriks ini'kan isi'nya kumpulan dari <i>array.</i>

## Iterasi

Kita juga dapat menerapkan iterasi(perulangan) dengan NumPy.<br>
Caranya sama seperti perulangan biasa pada Python dapat menggunakan <b>for</b> atau <b>while</b>.<br>
Berikut adalah contoh perulangan pada NumPy yang digunakan untuk mencetak nilai/elemen :

#### 1. <i>Array</i>

In [22]:
for i in BilPang2:
    print(i)

0
1
40
9
40
25
40
49
40
81


#### 2. Matriks

In [23]:
for baris in Matriks:
    print(baris)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


Isi elemen matriks NumPy adalah <i>array-array</i> yang dikumpulkan menjadi satu sehingga apabila kita menggunakan perulangan biasa untuk menampilkan elemen dari <b>Matriks</b> maka hasilnya adalah seperti di atas

Gunakan kata kunci <b>flat</b> untuk mencetak nilai dari tiap elemen pada matriks(dalam artian yang sesungguhnya).

In [24]:
for elemen in Matriks.flat:
    print(elemen)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## Fungsi Dasar(2)

Berikut adalah lanjutan penjelasan mengenai beberapa fungsi dasar pada NumPy :

<b>zeros_like()

Menmbuat <i>array</i>/matriks yang seluruh nilai elemen'nya 0 dari matriks rujukan.

In [25]:
x = np.arange(6)
x = x.reshape((2, 3))
print("Matriks rujukan:\n", x,"\n")
print("Matriks hasil zero_like():\n",np.zeros_like(x))

Matriks rujukan:
 [[0 1 2]
 [3 4 5]] 

Matriks hasil zero_like():
 [[0 0 0]
 [0 0 0]]


In [26]:
y = np.arange(3, dtype=float)
print("Matriks rujukan:\n", y,"\n")
print("Matriks hasil zero_like():\n",np.zeros_like(y))

Matriks rujukan:
 [0. 1. 2.] 

Matriks hasil zero_like():
 [0. 0. 0.]


Dari kedua contoh di atas dapat kita ketahui jika fungsi <b>zeros_like()</b> digunakan untuk memberi nilai kembalian pada <i>array</i>/matriks dengan nilai 0 sesuai dimensi/ukuran dari <i>array</i>/matriks awal(yang dijadikan contoh/dirujuk).

<b>empty()</b> dan <b>empy_like()

In [27]:
print(np.empty([4, 4], dtype=int))

[[    21850000 476741369971 489626271861 433791696995]
 [498216206368 468151435365 476741369968 416611827826]
 [450971566194 519691042924 502511173664 416611827822]
 [416611827830 463856468073 420906795105 433791697004]]


Membuat <i>array</i>/matriks baru dengan elemen matriks berupa alamat memori secara acak.<br>
Dimensi dari matriksnya harus disertakan, mau matriks berapa kali berapa.<br>
Untuk parameter <b>dtype</b> dapat tidak disertakan, tipe data <i>default</i> dari elemennya itu <i>float</i>.

In [28]:
a = ([1,2,3], [4,5,6]) 
print(np.empty_like(a))

[[32198784        0        0]
 [       0        0        0]]


Membuat <i>array</i>/matriks baru dengan elemen matriks berupa alamat memori secara acak dan dimensi yang sama dengan <i>array</i>/matriks awal(matriks yang dijadikan contoh/rujukan).

<b>append()</b>

Menambahkan elemen baru pada akhir <i>array</i>/matriks.<br>
Penggunaannya sama seperti <b>append</b> pada <i>list</i> Python.

In [29]:
print(np.append(BilPang2,112))

[  0   1  40   9  40  25  40  49  40  81 112]


Nilai baru tersebut tidak masuk ke dalam barisan elemen <i>array</i>/matriks.<br>
Berikut ini buktinya :

In [30]:
print(BilPang2)

[ 0  1 40  9 40 25 40 49 40 81]


Nah lo... <i>terus gimana caranya memasukkan nilai baru tersebut ke dalam NumPy array?</i><br>
Kalo ingin memasukkan ke dalam barisan elemen <i>array</i>/matriks ya tinggal masukkin ke variabel yang sama aja<br>
Ehehe.

In [31]:
BilPang2 = np.append(BilPang2,112)
print(BilPang2)

[  0   1  40   9  40  25  40  49  40  81 112]


<b>delete()

Kalo barusan itu buat nambah data...<br>
Yup sesuai dengan namanya, fungsi <b>delete</b> berguna untuk menghapus elemen berdasarkan indeks dari sebuah <i>array</i>/matriks.<br>
Penggunaannya sama seperti <b>delete</b> pada <i>list</i> Python.

In [32]:
print(np.delete(BilPang2, -1))

[ 0  1 40  9 40 25 40 49 40 81]


Nilai yang barusan dihapus tersebut ndak keluar dari barisan elemen <i>array</i>/matriks.<br>
Ini nih buktinya :

In [33]:
print(BilPang2)

[  0   1  40   9  40  25  40  49  40  81 112]


Sama seperti fungsi <b>append</b>, kalo ingin menghapus elemen ke luar dari barisan elemen array/matriks ya tinggal masukkin ke variabel yang sama aja
Ehehe.

In [34]:
BilPang2 = np.delete(BilPang2, -1)
print(BilPang2)

[ 0  1 40  9 40 25 40 49 40 81]


Sekian dari saya semoga bermanfaat!