NumPy sangat memudahkan kita untuk merubah bentuk suatu <i>array</i>/matriks.<br>
Baik itu menggabungkan beberapa <i>array</i>/matriks menjadi satu sampai memisah-misah(membagi) <i>array</i>/matriks ke dalam bagian yang lebih kecil lagi.<br>
Seperti biasa, awali dengan dengan impor modul.

In [1]:
import numpy as np

Beberapa kata kunci/fungsi dari NumPy yang digunakan untuk manipulasi bentuk pada NumPy, yakni :<br>
<b>shape<br>
ravel()<br>
resize()<br>
reshape()<br>
T<br></b>

Adapun <i>tuple</i> untuk menggabungkan <i>array</i>/matriks yang hendak saya jelaskan, antara lain :<br>
<b>vstack()<br>
hstack()<br>
column_stack()</b><br>

Serta fungsi untuk memisahkan <i>array</i>/matriks ke dalam bagian yang kecil, yaitu :<br>
<b>split()<br>
vsplit()<br>
hsplit()<br>
array_split()</b><br>

Monggo disimak baik-baik :)

## Merubah bentuk <i>array</i>/matriks

In [2]:
a = np.arange(30)   # Buat numpy array
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


Cara merubah bentuk pada NumPy array sangat mudah.<br>
Jika menggunakan kata kunci <b>shape</b> maka formatnya adalah seperti ini :<br>

<b>nama_array.shape(jumlah_baris, jumlah_kolom)</b>

In [3]:
a.shape = (5,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


<b>ravel()

Fungsi <b>ravel()</b> berguna untuk untuk menjadikan matriks dalam bentuk(ukuran) apapun menjadi <i>array</i> satu dimensi.<br>
Format penulisan :<br>
<b>nama_array.ravel()

In [4]:
print(a.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


<b>resize()

Fungsi fungsi <b>resize()</b> sama dengan kata kunci <b>shape</b> yang membedakan hanyalah cara penulisannya saja.<br>
format penulisan :<br><b>nama_array.resize(jumlah_baris, jumlah_kolom)

In [5]:
a.resize(3,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


<b>reshape()</b>

Fungsinya sama seperti resize() hanya saja bentuk yang telah dirubah tidaklah merubah bentuk asli.<br>
Format penulisan :<br>
<b>np.reshape(nama_array, (jumlah_baris, jumlah_kolom))</b>

In [6]:
print(np.reshape(a, (10,3)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


Berikut ini buktinya :

In [7]:
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


Agar bentuk aslinya berubah cukup masukkan saja nilanya ke dalam variabel yang sama

In [8]:
a = np.reshape(a, (10,3))
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


Matriks transpose dari variabel a adalah matriks yang diperoleh dengan cara menukar elemen pada baris menjedi elemen pada kolom.<br>
Pada NumPy terdapat kata kunci yang bisa kita gunakan untuk mentransposekan sebuah matriks, yaitu <b>T</b>.<br>

In [9]:
print(a.T)

[[ 0  3  6  9 12 15 18 21 24 27]
 [ 1  4  7 10 13 16 19 22 25 28]
 [ 2  5  8 11 14 17 20 23 26 29]]


## Menggabungkan <i>array</i>/matriks

Kita bikin matriks baru aja ya...<br>
Ehehehe

In [10]:
b = np.array(([1,2],[3,4]))
print(b)

[[1 2]
 [3 4]]


In [11]:
c = np.array(([5,6],[7,8]))
print(c)

[[5 6]
 [7 8]]


<b>vstack()

In [12]:
print(np.vstack((b,c)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Kepanjangan dari <b>vstack</b> sendiri adalah <i>vertical stack</i>.<br>
Jadi <b>vstack</b> adalah sebuah <a href="https://docs.python.org/3.6/tutorial/datastructures.html#tuples-and-sequences">tuple</a>(bukan fungsi) yang dapat digunakan untuk menumpuk <i>array</i>/matriks secara vertikal.

<b>hstack()

In [13]:
print(np.hstack((b,c)))

[[1 2 5 6]
 [3 4 7 8]]


Fungsinya sama seperti vstack yang membedakan hanyalah bentuk penggabungan'nya.<br>
Kepanjangan dari <b>hstack</b> sendiri adalah <i>horizontal stack</i>.<br>
Jadi <b>hstack</b> adalah sebuah <a href="https://docs.python.org/3.6/tutorial/datastructures.html#tuples-and-sequences">tuple</a>(bukan fungsi) yang dapat digunakan untuk menumpuk <i>array</i>/matriks secara horizontal.

<b>column_stack()

In [14]:
d = np.array(([1,2,3]))
e = np.array(([4,5,6]))
f = np.array(([7,8,9]))
print("Array d :", d)
print("Array e :", e)
print("Array f :", f)

Array d : [1 2 3]
Array e : [4 5 6]
Array f : [7 8 9]


Fungsi dari tuple <b>column_stack</b> adalah untuk menggabungkan <i>array</i> satu dimensi menjadi matriks(dua dimensi).<br>
Namun <i>array</i> satu dimensi tersebut nantinya akan menjadi kolom bukan baris.

In [15]:
print(np.column_stack((d, e, f)))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## Memisah satu <i>array</i>/matriks menjadi <i>array</i>/matriks yang lebih kecil

Bikin matriks baru lagi.<br>
Biar enakan.

In [16]:
g = np.arange(16)*2
h = g.reshape(4,4)
print("Array g :", g,"\n")
print("Matriks h :\n", h)

Array g : [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30] 

Matriks h :
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]


<b>split()

Digunakan untuk memisah <i>array</i>/matriks dengan syarat jumlah elemen dari tiap hasil <i>array</i>/matriks yg telah terbagi harus sama.

In [17]:
print(np.split(g, 2), "\n")
print(np.split(h, 2))

[array([ 0,  2,  4,  6,  8, 10, 12, 14]), array([16, 18, 20, 22, 24, 26, 28, 30])] 

[array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]]), array([[16, 18, 20, 22],
       [24, 26, 28, 30]])]


Apabila kita memisah dengan jumlah yang tidak sama :

In [18]:
print(np.split(g, 3))

ValueError: array split does not result in an equal division

<b>hsplit()

Digunakan untuk memisah <i>array</i>/matriks secara horizontal.

In [19]:
print(np.hsplit(g,4))   # sudah jelas bisa lah -_-

[array([0, 2, 4, 6]), array([ 8, 10, 12, 14]), array([16, 18, 20, 22]), array([24, 26, 28, 30])]


In [20]:
print(np.hsplit(h,2))

[array([[ 0,  2],
       [ 8, 10],
       [16, 18],
       [24, 26]]), array([[ 4,  6],
       [12, 14],
       [20, 22],
       [28, 30]])]


<b>vsplit()</b>

Digunakan untuk memisah matriks secara vertikal.<br>

In [21]:
print(np.vsplit(h, 2))

[array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]]), array([[16, 18, 20, 22],
       [24, 26, 28, 30]])]


Tidak dapat digunakan pada <i>array</i> satu dimensi.

In [22]:
print(np.vsplit(g,4))

ValueError: vsplit only works on arrays of 2 or more dimensions

<b>array_split()</b>

Sama seperti fungsi <b>split</b>, <b>array_split</b> digunakan untuk memisah <i>array</i>/matriks.<br>
Yang membuat mereka berbeda adalah pada <b>array_split</b> jumlah elemen dari tiap <i>array</i>/matriks yang telah terbagi tidak harus sama(boleh berbeda).

In [23]:
print(np.array_split(g, 5))

[array([0, 2, 4, 6]), array([ 8, 10, 12]), array([14, 16, 18]), array([20, 22, 24]), array([26, 28, 30])]


Sekian dari saya semoga bermanfaat!